	<main id="content" role="main">
		<div class="container container-boxes">
			<div class="row">
				<div class="col-sm-6">
					<div class="box white-bg">
						<h1 class="title-404">Error 404 Page not found</h1>
						<p>Apologies, but no results were found for the requested page. Perhaps searching will help find a related item or</p>
						<p class="no-bottom"><a href="<?php echo SITE_PATH ;?>" class="button">Go Home</a></p>
					</div>
					<div class="box white-bg text-center">
						<h5 class="no-bottom">Connect with us</h5>
						<p>Follow us, send us feedbacks and help us grow together.</p>
						<div class="col-md-6 col-md-offset-3">
							<div class="col-xs-6 col-sm-6 p-x-0">
					            <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fmytrouper%2F&width=100&layout=button&action=like&size=small&show_faces=false&share=true&height=50&appId=279347922476477" width="100" height="50" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <div class="g-follow" data-annotation="none" data-height="20" data-href="https://plus.google.com/112798600567989135542" data-rel="author"></div>
                            </div>
                            <div class="clearfix"></div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="box white-bg text-center">
						<div class="col-md-12">
							<h5 class="twitter-follow-text">Please share us with friends and families and help us to grow our community.</h5>
							<h6 class="text-center no-bottom">Share</h6>
							<div class="addthis_inline_share_toolbox_k9or"></div>
						</div>
						<div class="clearfix"></div>
					</div>
					<div class="box">
						<img src="<?php echo SITE_PATH ;?>res/img/404-image.jpg" width="800" height="800" alt="">
					</div>
				</div>
			</div>
		</div>
	</main>