<div id="main" class="unknown-page">
		<!-- header -->
		<div id="header">
			<h1 style="font-size: 50px; line-height: 1.1em; font-weight: normal; color: darkgray; font-family: sans-serif; text-align: center; padding: 94px 0 0 0; text-transform: capitalize; font-variant: small-caps; letter-spacing: -2px;">
				Site is Under Maintenance<span>
			
			</span></h1>
			<div class="container" style="text-align: center;font-size:6em;   width: 100%; ">
	<h2 style=" text-shadow: 4px 3px 0px #fff, 9px 8px 0px rgba(0,0,0,0.15);  
	color:#EF4036;
	margin-top:0%;
	margin-bottom:0%;font-size:100px;">503 Error</h2></div>
		</div>
		<!-- content -->
		<div id="content">


			<p style="text-align: center; padding: 0 35px;; margin-bottom: 8px; font-size: 21px; font-family: cursive;">
				We're sorry but Please visit after some time<br>
			</p>

		</div>


	</div>