<?php 
	$fun = new DatabaseFunctions();
	$func = new functions();
?>
<main id="content" role="main">
	<div class="container container-boxes">
		<div class="row">
			<div class="col-sm-6">
				<div class="box white-bg" style="background-image:url(<?=SITE_PATH?>res/img/contact.jpg)">
					<h1>Contact Us</h1>
					<p>Below are some info on how to reach out to us. <br></p>
					<p class="small contact-address-info">
						<i class="fa fa-map-marker"></i>
						#14, 24th Main, BTM Layout<br>
						Bangalore, IN
					</p>
					<p class="small contact-address-info">
						<i class="fa fa-envelope"></i>
						hi@mytrouper.com
					</p>
					<p class="small contact-address-info">
						<i class="fa fa-phone"></i>
						+91 99862 49236<br>
						+91 90664 45730
					</p>
				</div>
				<div class="box white-bg text-center">
					<h5>Connect with us</h5>
					<p>Follow us, send us your work, share something cool you did in your latest project</p>
					<p class="social-share no-bottom">
						<?php 
							if(SITE_TWITTER != ""){
						?>
								<a href="<?=SITE_TWITTER?>" class="social-link"><i class="fa fa-twitter"></i></a>
						<?php
							}
							if(SITE_GP != ""){
						?>
								<a href="<?=SITE_GP?>" class="social-link"><i class="fa fa-google-plus"></i></a>
						<?php 
							}
							if(SITE_YOU_TUBE != ""){
						?>
								<a href="<?=SITE_YOU_TUBE?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php
							}
							if(SITE_FB != ""){
						?>
								<a href="<?=SITE_FB?>" class="social-link"><i class="fa fa-facebook"></i></a>
						<?php		
							}
							if(SITE_INSTRAGRAM != ""){
						?>
								<a href="<?=SITE_INSTRAGRAM?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php		
							}
							if(SITE_PINTEREST != ""){
						?>
								<a href="<?=SITE_PINTEREST?>" class="social-link"><i class="fa fa-pinterest"></i></a>
						<?php	
							}
							if(SITE_DRIBBLE != ""){
						?>
								<a href="<?=SITE_DRIBBLE?>" class="social-link"><i class="fa fa-dribbble"></i></a>
						<?php	
							}
							if(SITE_BEWHANCE != ""){
						?>
								<a href="<?=SITE_BEWHANCE?>" class="social-link"><i class="fa fa-behance"></i></a>
						<?php	
							}
						?>
					</p>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="box white-bg text-center">
					<div class="col-md-6">
						<p class="twitter-follow">
							<a href="#" class="username"><i class="fa fa-twitter"></i>@mytrouper</a>
							<a href="#" class="button">Follow</a>
						</p>
					</div>
					<div class="col-md-6">
						<h5 class="twitter-follow-text no-bottom">Follow us to catch the latest buzz. Join our 800k+ followers</h5>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="box white-bg">
					<h5>Send message</h5>
					<div class="sep red"></div>
					<div class="margin-1"></div>
					<form action="contact1.html" class="no-bottom">
						<label for="name" class="sr-only">Name</label>
						<input type="text" class="underline" name="name" id="name" placeholder="Your name..." required="">
						<label for="email" class="sr-only">Email</label>
						<input type="email" class="underline" name="email" id="email" placeholder="Your email..." required="">
						<label for="message" class="sr-only">Message</label>
						<textarea class="underline" name="message" id="message" cols="30" rows="6" placeholder="Here goes the message..." required=""></textarea>
						<div class="margin-1"></div>
						<input type="submit" value="Send it">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>