<?php 
	$fun = new DatabaseFunctions();
	$func = new functions();
?>
<main id="content" role="main">
	<div class="container container-boxes">
		<div class="row">
			<div class="col-sm-6">
				<div class="box white-bg" style="background-image:url(<?=SITE_PATH?>res/img/contact.jpg)">
					<h1>Contact Us</h1>
					<p>Below are some info on how to reach out to us. <br></p>
					<p class="small contact-address-info">
						<i class="fa fa-map-marker"></i>
						#14, 24th Main, BTM Layout<br>
						Bangalore, IN
					</p>
					<p class="small contact-address-info">
						<i class="fa fa-envelope"></i>
						hi@mytrouper.com
					</p>
					<p class="small contact-address-info">
						<i class="fa fa-phone"></i>
						+91 99862 49236<br>
						+91 90664 45730
					</p>
				</div>
				<div class="box white-bg text-center">
					<h5>Connect with us</h5>
					<p>Follow us, send us feedbacks and help us grow together.</p>
					<div class="col-md-6 col-md-offset-3">
						<div class="col-xs-6 col-sm-6 p-x-0">
				            <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fmytrouper%2F&width=100&layout=button&action=like&size=small&show_faces=false&share=true&height=50&appId=279347922476477" width="100" height="50" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                        </div>
                        <div class="col-xs-6 col-sm-6">
                            <div class="g-follow" data-annotation="none" data-height="20" data-href="https://plus.google.com/112798600567989135542" data-rel="author"></div>
                        </div>
                        <div class="clearfix"></div>
					</div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="box white-bg text-center">
					<div class="col-md-12">
							<h5 class="twitter-follow-text">Please share us with friends and families and help us to grow our community.</h5>
							<h6 class="text-center no-bottom">Share</h6>
							<div class="addthis_inline_share_toolbox_k9or"></div>
						</div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="box white-bg">
					<h5>Send message</h5>
					<div class="sep red"></div>
					<div class="margin-1"></div>
					<form action="contact1.html" class="no-bottom">
						<label for="name" class="sr-only">Name</label>
						<input type="text" class="underline" name="name" id="name" placeholder="Your name..." required="">
						<label for="email" class="sr-only">Email</label>
						<input type="email" class="underline" name="email" id="email" placeholder="Your email..." required="">
						<label for="message" class="sr-only">Message</label>
						<textarea class="underline" name="message" id="message" cols="30" rows="6" placeholder="Here goes the message..." required=""></textarea>
						<div class="margin-1"></div>
						<input type="submit" value="Send it">
					</form>
				</div>
			</div>
		</div>
	</div>
</main>