<?php
	$fun = new DatabaseFunctions();
	$func = new functions();
?>
		<footer id="footer" role="contentinfo">
			<div class="container">
				<p>
					<a href="<?= SITE_PATH ?>" class="mini-logo"><img src="<?= SITE_PATH ?>res/img/logo.png" width="90" height="33" alt="Exa"></a>
				</p>
				<p>&copy; <?=date('Y')?> <a href="<?=SITE_PATH?>" title="MyTrouper"  target="_blank">MyTrouper</a>. All Rights Reserved.</p>
				<p>
					<?php
							if(SITE_TWITTER != ""){
						?>
								<a href="<?=SITE_TWITTER?>" class="social-link"><i class="fa fa-twitter"></i></a>
						<?php
							}
							if(SITE_GP != ""){
						?>
								<a href="<?=SITE_GP?>" class="social-link"><i class="fa fa-google-plus"></i></a>
						<?php
							}
							if(SITE_YOU_TUBE != ""){
						?>
								<a href="<?=SITE_YOU_TUBE?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php
							}
							if(SITE_FB != ""){
						?>
								<a href="<?=SITE_FB?>" class="social-link"><i class="fa fa-facebook"></i></a>
						<?php
							}
							if(SITE_INSTRAGRAM != ""){
						?>
								<a href="<?=SITE_INSTRAGRAM?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php
							}
							if(SITE_PINTEREST != ""){
						?>
								<a href="<?=SITE_PINTEREST?>" class="social-link"><i class="fa fa-pinterest"></i></a>
						<?php
							}
							if(SITE_DRIBBLE != ""){
						?>
								<a href="<?=SITE_DRIBBLE?>" class="social-link"><i class="fa fa-dribbble"></i></a>
						<?php
							}
							if(SITE_BEWHANCE != ""){
						?>
								<a href="<?=SITE_BEWHANCE?>" class="social-link"><i class="fa fa-behance"></i></a>
						<?php
							}
						?>
				</p>
			</div>
		</footer>
		
		<script type="text/javascript" src="<?= SITE_PATH ?>res/js/owl.carousel.min.js"></script>
		<script type="text/javascript" src="<?= SITE_PATH ?>res/js/audio-player.js"></script>
		<script src="<?= SITE_PATH ?>res/js/modernizr.custom.js"></script>
		<script src="<?= SITE_PATH ?>res/js/notification.js"></script>
		<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5910d0571fdde1d3"></script> 
		<script>
		
		    // NOTE: for notification
    		function notify($typ,$msg,$lay,$eft){
    			// create the notification
    			var notification = new NotificationFx({
    				message : $msg,
    				layout : $lay || 'growl',
    				effect : $eft || 'jelly',
    				type : $typ, // notice, warning, error or success
    				onClose : function() {
    
    				}
    			});
    
    			// show the notification
    			notification.show();
    		}

			jQuery(".owl-carousel.owl-thumbs").owlCarousel({
				items   : 4,
				margin  : 30,
				nav     : true,
				navText : ['', ''],
				dots    : false,
				loop    : false,
				responsive : {
					0: {
						items : 2
					},
					768: {
						items : 3
					},
					992: {
						items : 4
					}
				}
			});
			jQuery(".owl-carousel.owl-testimonials2").owlCarousel({
				items   : 1,
				nav     : false,
				navText : ['', ''],
				dots    : true,
				loop    : true
			});
		</script>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        
          ga('create', 'UA-99141999-1', 'auto');
          ga('send', 'pageview');
        
        </script>
        <script type="application/ld+json">
        {
          "@context": "http://schema.org",
          "@type": "Organization",
          "url": "http://www.mytrouper.com",
          "logo": "http://www.mytrouper.com/res/img/logo.png"
        }
        </script>
	</body>
</html>
