<?php
	$fun = new DatabaseFunctions();
	$func = new functions();
	$func->audio_player();
?>
		<footer id="footer" role="contentinfo">
			<div class="container">
				<p>
					<a href="<?= SITE_PATH ?>" class="mini-logo"><img src="<?= SITE_PATH ?>res/img/logo.png" width="90" height="33" alt="Exa"></a>
				</p>
				<p>&copy; <?=date('Y')?> <a href="http://www.trikoninfosystems.com/" title="Trikon Infosystems"  target="_blank">Trikon Infosystems</a>. All Rights Reserved.</p>
				<p>
					<?php
							if(SITE_TWITTER != ""){
						?>
								<a href="<?=SITE_TWITTER?>" class="social-link"><i class="fa fa-twitter"></i></a>
						<?php
							}
							if(SITE_GP != ""){
						?>
								<a href="<?=SITE_GP?>" class="social-link"><i class="fa fa-google-plus"></i></a>
						<?php
							}
							if(SITE_YOU_TUBE != ""){
						?>
								<a href="<?=SITE_YOU_TUBE?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php
							}
							if(SITE_FB != ""){
						?>
								<a href="<?=SITE_FB?>" class="social-link"><i class="fa fa-facebook"></i></a>
						<?php
							}
							if(SITE_INSTRAGRAM != ""){
						?>
								<a href="<?=SITE_INSTRAGRAM?>" class="social-link"><i class="fa fa-youtube"></i></a>
						<?php
							}
							if(SITE_PINTEREST != ""){
						?>
								<a href="<?=SITE_PINTEREST?>" class="social-link"><i class="fa fa-pinterest"></i></a>
						<?php
							}
							if(SITE_DRIBBLE != ""){
						?>
								<a href="<?=SITE_DRIBBLE?>" class="social-link"><i class="fa fa-dribbble"></i></a>
						<?php
							}
							if(SITE_BEWHANCE != ""){
						?>
								<a href="<?=SITE_BEWHANCE?>" class="social-link"><i class="fa fa-behance"></i></a>
						<?php
							}
						?>
				</p>
			</div>
		</footer>

		<script type="text/javascript" src="<?= SITE_PATH ?>res/js/owl.carousel.min.js"></script>
		<script type="text/javascript" src="<?= SITE_PATH ?>res/js/audio-player.js"></script>
		<script src="<?= SITE_PATH ?>res/js/moment.js" type="text/javascript"></script>
		<script src="<?= SITE_PATH ?>res/js/jquery.eventCalendar.js" type="text/javascript"></script>
		<script src="<?= SITE_PATH ?>res/js/modernizr.custom.js"></script>
		<script src="<?= SITE_PATH ?>res/js/notification.js"></script>
		<script>

		// NOTE: for notification
		function notify($typ,$msg,$lay,$eft){
			// create the notification
			var notification = new NotificationFx({
				message : $msg,
				layout : $lay || 'growl',
				effect : $eft || 'jelly',
				type : $typ, // notice, warning, error or success
				onClose : function() {

				}
			});

			// show the notification
			notification.show();
		}

			jQuery(".owl-carousel.owl-thumbs").owlCarousel({
				items   : 4,
				margin  : 30,
				nav     : true,
				navText : ['', ''],
				dots    : false,
				loop    : false,
				responsive : {
					0: {
						items : 2
					},
					768: {
						items : 3
					},
					992: {
						items : 4
					}
				}
			});
			jQuery(".owl-carousel.owl-testimonials2").owlCarousel({
				items   : 1,
				nav     : false,
				navText : ['', ''],
				dots    : true,
				loop    : true
			});
		</script>

	</body>
</html>
