<?php 
	$index_obj = new index();
	$featured_artist = json_decode($index_obj->featured_artist());
?>
<main id="content" role="main">
	<div class="container container-masonry">
		<div class="inner">
			<div class="row">
				<div class="box col-sm-4 col-md-6">
					<div class="thumb featured">
						<div class="photo searchpanel" style="background-image:url('<?= SITE_PATH ?>res/img/search_bg.jpg')">
							<span class="info"><h3 class="no-bottom">Search <span class="hidden-xs">Your </span>Artiste</h3> <h6 class="text-red">www.MyTrouper.com</h6>
									<span class="excerpt">An online artist booking platform and a great place to showcase works online for singers and all kinds of entertainers.</span>
								<form class="search-container">
								<input type="text" id="search-bar" placeholder="Search here for favourite artist">
								<a href="#" class="search-icon"><span class="fa fa-search"></span></a>
							  </form>
							  <div class="col-xs-9 row" style="position:absolute; bottom:0;">
							        <div class="col-xs-6 col-sm-3 p-x-0">
							            <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fmytrouper%2F&width=100&layout=button&action=like&size=small&show_faces=false&share=true&height=50&appId=279347922476477" width="100" height="50" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
                                    </div>
                                    <div class="col-xs-6 col-sm-3">
                                        <div class="g-follow" data-annotation="none" data-height="20" data-href="https://plus.google.com/112798600567989135542" data-rel="author"></div>
                                    </div>
                                    
							  </div>
							</span>
						</div>
					</div>
				</div>
				<div class="box col-xs-6 col-sm-4 col-md-3">
					<div class="thumb">
						<div class="photo">
							<a href="<?= SITE_PATH.'artist'?>">
								<img src="<?= SITE_PATH ?>res/img/artist_bg.jpg" alt="" width="434" height="434">
								<span class="info visible-xs"><strong class="title">Artist</strong><span class="excerpt">Find & connect of your favourite singer and artist.</span><em class="arrow-right"></em></span>
							</a>
						</div>
					</div>
				</div>
				<div class="box col-xs-6 col-sm-4 col-md-3">
					<div class="thumb">
						<div class="photo">
							<a href="<?= SITE_PATH.'songs'?>">
								<img src="<?= SITE_PATH ?>res/img/song_bg.jpg" alt="" width="434" height="434">
								<span class="info  visible-xs"><strong class="title">Songs</strong><span class="excerpt">Listen to our best collection of songs.</span><em class="arrow-right"></em></span>
							</a>
						</div>
					</div>
				</div>
				<div class="box col-xs-6 col-sm-4 col-md-3">
					<div class="thumb">
						<div class="photo">
							<a href="<?= SITE_PATH.'videos'?>">
								<img src="<?= SITE_PATH ?>res/img/video_bg.jpg" alt="" width="434" height="434">
								<span class="info visible-xs"><strong class="title">Videos</strong><span class="excerpt">Best collection of Assamese Videos Playlist.</span><em class="arrow-right"></em></span>
							</a>
						</div>
					</div>
				</div>
				<div class="box col-xs-6 col-sm-4 col-md-3">
					<div class="thumb">
						<div class="photo">
							<a href="<?= SITE_PATH.''?>">
								<img src="<?= SITE_PATH ?>res/img/event_bg.jpg" alt="" width="434" height="434">
								<span class="info visible-xs"><strong class="title">Events</strong><span class="excerpt">Get to know about the events near your place.</span><em class="arrow-right"></em></span>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="clear"></div>

		<div class="margin-1"></div>
		<?php 
			if(!empty($featured_artist)){
		?>
			<div class="row">
				<div class="box col-xs-6 col-sm-8 col-md-9">
					<h6>Artist</h6>
					<div class="sep red margin-1"></div>
				</div>
				<div class="box col-xs-6 col-sm-4 col-md-3">
					<a href="<?=SITE_PATH?>signup" class="button filled pull-right">Join The Community</a>
				</div>
			</div>
			<div class="owl-carousel owl-thumbs owl-theme">
			<?php 
				foreach($featured_artist as $key=>$value){
			?>
					<div class="thumb">
						<div class="photo">
							<a href="<?=SITE_PATH.'profile/'.$value->title_clean?>">
								<img src="<?=$value->image?>" alt="" width="434" height="434">

								<span class="info"><span class="big-excerpt"><?=$value->name?></span></span>
							</a>
						</div>
					</div>
				<?php } ?>
			</div>
		<?php } ?>
		<div class="margin-4"></div>

	</div>
</main>