<main id="content" role="main">
		<div class="container container-boxes">
			<div class="row">
				<div class="col-sm-6">
					<div class="box white-bg" style="background-image:url(<?=SITE_PATH?>res/img/contact.jpg)">
						<h2>Artist Login</h2>
						<div class="sep red"></div>
						<p>Please use social login. <br>
							<a href="<?=SITE_PATH?>/theme/modules/login-with-facebook/fbconfig.php" class="button filled pull-right">Facebook Login</a>
						</p>
						<!--<div class="fb-login-button" data-max-rows="1" data-size="large" data-show-faces="true" data-auto-logout-link="true"></div>
						<div id="fb-root"></div>
						<script>(function(d, s, id) {
						  var js, fjs = d.getElementsByTagName(s)[0];
						  if (d.getElementById(id)) return;
						  js = d.createElement(s); js.id = id;
						  js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=<?=FB_APP_ID?>";
						  fjs.parentNode.insertBefore(js, fjs);
						}(document, 'script', 'facebook-jssdk'));</script>-->
						<a href="#">Need Help?</a>
					</div>
				</div>

				<div class="col-sm-6">
					<div class="box white-bg">
						<h2>Committee Login</h2>
						<div class="sep red"></div>
						<div class="margin-1"></div>
						<form action="contact1.html" class="no-bottom">
							<label for="name" class="sr-only">Email</label>
							<input type="text" class="underline" name="email" id="name" placeholder="Your email..." required="">
							<label for="email" class="sr-only">Password</label>
							<input type="email" class="underline" name="password" id="email" placeholder="Your password..." required="">
							<div class="margin-1"></div>
							<input type="submit" value="Login">
						</form>
					</div>
				</div>
			</div>
		</div>
	</main>