<main id="content" role="main">
		<div class="container container-boxes">
			<div class="row">
				<div class="col-sm-6">
					<div class="box white-bg" style="background-image:url(<?=SITE_PATH?>res/img/artist_bg.jpg)">
						<h3>Artist Login</h3>
						<div class="sep red"></div>
						<p>Please use social login. </p>
						<div class="row">
						    <div class="col-xs-6 col-md-4">
						        <a href="<?=ACTION_URL?>" class="button filled col-xs-12" style="background:#3b5998; border:0"><i class="fa fa-facebook"></i> Facebook</a>
						    </div>
						    <div class="col-xs-6 col-md-4">
						        <a href="<?=GOOGLE_ACTION_URI?>" class="button filled col-xs-12" style="background:#dd4b39; border:0"><i class="fa fa-google-plus"></i> Google +</a>
						    </div>
						    <div class="col-xs-6 col-md-4">
						        <a href="<?=TWITTER_ACTION_URI?>" class="button filled col-xs-12" style="background:#1da1f2; border:0"><i class="fa fa-twitter"></i> Twitter</a>
						    </div>
							
						</div>
						
						<a href="mailto:info@mytrouper.com">Need Help?</a>
						<div class="margin-5"></div>
						<div class="margin-5"></div>
					</div>
				</div>

				<div class="col-sm-6">
					<div class="box white-bg">
						<h3>Committee Login</h3>
						<div class="sep red"></div>
						<div class="margin-1"></div>
						<form action="contact1.html" class="no-bottom">
							<label for="name" class="sr-only">Email</label>
							<input type="text" class="underline" name="email" id="name" placeholder="Your email..." required="">
							<label for="email" class="sr-only">Password</label>
							<input type="email" class="underline" name="password" id="email" placeholder="Your password..." required="">
							<div class="margin-1"></div>
							<input type="submit" value="Login">
						</form>
					</div>
				</div>
			</div>
		</div>
	</main>